# script generated by Claude AI and modified by Thibaut Baguette

import subprocess
import re
import pandas as pd
import random


COMMAND = "cargo run --release --example=render"  # The command-line program to run


BATCH = [
    # cornelbox 1spp
    {"input": "02_cornelbox", "mod": "linear", "spp": 1, "runs": 10},
    {"input": "02_cornelbox", "mod": "spatial-longest", "spp": 1, "runs": 10},
    {"input": "02_cornelbox", "mod": "spatial-random", "spp": 1, "runs": 10},
    {"input": "02_cornelbox", "mod": "spatial-robin", "spp": 1, "runs": 10},
    {"input": "02_cornelbox", "mod": "median-longest", "spp": 1, "runs": 10},
    {"input": "02_cornelbox", "mod": "median-random", "spp": 1, "runs": 10},
    {"input": "02_cornelbox", "mod": "median-robin", "spp": 1, "runs": 10},
    {"input": "02_cornelbox", "mod": "sah", "spp": 1, "runs": 10},
    # cornelbox 32spp
    {"input": "02_cornelbox", "mod": "linear", "spp": 32, "runs": 10},
    {"input": "02_cornelbox", "mod": "spatial-longest", "spp": 32, "runs": 10},
    {"input": "02_cornelbox", "mod": "spatial-random", "spp": 32, "runs": 10},
    {"input": "02_cornelbox", "mod": "spatial-robin", "spp": 32, "runs": 10},
    {"input": "02_cornelbox", "mod": "median-longest", "spp": 32, "runs": 10},
    {"input": "02_cornelbox", "mod": "median-random", "spp": 32, "runs": 10},
    {"input": "02_cornelbox", "mod": "median-robin", "spp": 32, "runs": 10},
    {"input": "02_cornelbox", "mod": "sah", "spp": 32, "runs": 10},
    # cornelbox 128spp
    {"input": "02_cornelbox", "mod": "linear", "spp": 128, "runs": 3},
    {"input": "02_cornelbox", "mod": "spatial-longest", "spp": 128, "runs": 3},
    {"input": "02_cornelbox", "mod": "spatial-random", "spp": 128, "runs": 3},
    {"input": "02_cornelbox", "mod": "spatial-robin", "spp": 128, "runs": 3},
    {"input": "02_cornelbox", "mod": "median-longest", "spp": 128, "runs": 3},
    {"input": "02_cornelbox", "mod": "median-random", "spp": 128, "runs": 3},
    {"input": "02_cornelbox", "mod": "median-robin", "spp": 128, "runs": 3},
    {"input": "02_cornelbox", "mod": "sah", "spp": 128, "runs": 3},
    # spaceship 1spp
    {"input": "02_spaceship", "mod": "spatial-longest", "spp": 1, "runs": 10},
    {"input": "02_spaceship", "mod": "spatial-random", "spp": 1, "runs": 10},
    {"input": "02_spaceship", "mod": "spatial-robin", "spp": 1, "runs": 10},
    {"input": "02_spaceship", "mod": "median-longest", "spp": 1, "runs": 10},
    {"input": "02_spaceship", "mod": "median-random", "spp": 1, "runs": 10},
    {"input": "02_spaceship", "mod": "median-robin", "spp": 1, "runs": 10},
    {"input": "02_spaceship", "mod": "sah", "spp": 1, "runs": 10},
    # spaceship 32spp
    {"input": "02_spaceship", "mod": "spatial-longest", "spp": 32, "runs": 10},
    {"input": "02_spaceship", "mod": "spatial-random", "spp": 32, "runs": 10},
    {"input": "02_spaceship", "mod": "spatial-robin", "spp": 32, "runs": 10},
    {"input": "02_spaceship", "mod": "median-longest", "spp": 32, "runs": 10},
    {"input": "02_spaceship", "mod": "median-random", "spp": 32, "runs": 10},
    {"input": "02_spaceship", "mod": "median-robin", "spp": 32, "runs": 10},
    {"input": "02_spaceship", "mod": "sah", "spp": 32, "runs": 10},
    # spaceship 128spp
    {"input": "02_spaceship", "mod": "spatial-longest", "spp": 128, "runs": 3},
    {"input": "02_spaceship", "mod": "spatial-random", "spp": 128, "runs": 3},
    {"input": "02_spaceship", "mod": "spatial-robin", "spp": 128, "runs": 3},
    {"input": "02_spaceship", "mod": "median-longest", "spp": 128, "runs": 3},
    {"input": "02_spaceship", "mod": "median-random", "spp": 128, "runs": 3},
    {"input": "02_spaceship", "mod": "median-robin", "spp": 128, "runs": 3},
    {"input": "02_spaceship", "mod": "sah", "spp": 128, "runs": 3},
    # classic 1spp
    {"input": "02_classic", "mod": "linear", "spp": 1, "runs": 1},
    {"input": "02_classic", "mod": "spatial-longest", "spp": 1, "runs": 10},
    {"input": "02_classic", "mod": "spatial-random", "spp": 1, "runs": 10},
    {"input": "02_classic", "mod": "spatial-robin", "spp": 1, "runs": 10},
    {"input": "02_classic", "mod": "median-longest", "spp": 1, "runs": 10},
    {"input": "02_classic", "mod": "median-random", "spp": 1, "runs": 10},
    {"input": "02_classic", "mod": "median-robin", "spp": 1, "runs": 10},
    {"input": "02_classic", "mod": "sah", "spp": 1, "runs": 10},
    # classic 32spp
    {"input": "02_classic", "mod": "spatial-longest", "spp": 32, "runs": 10},
    {"input": "02_classic", "mod": "spatial-random", "spp": 32, "runs": 10},
    {"input": "02_classic", "mod": "spatial-robin", "spp": 32, "runs": 10},
    {"input": "02_classic", "mod": "median-longest", "spp": 32, "runs": 10},
    {"input": "02_classic", "mod": "median-random", "spp": 32, "runs": 10},
    {"input": "02_classic", "mod": "median-robin", "spp": 32, "runs": 10},
    {"input": "02_classic", "mod": "sah", "spp": 32, "runs": 10},
    # classic 128spp
    {"input": "02_classic", "mod": "spatial-longest", "spp": 128, "runs": 3},
    {"input": "02_classic", "mod": "spatial-random", "spp": 128, "runs": 3},
    {"input": "02_classic", "mod": "spatial-robin", "spp": 128, "runs": 3},
    {"input": "02_classic", "mod": "median-longest", "spp": 128, "runs": 3},
    {"input": "02_classic", "mod": "median-random", "spp": 128, "runs": 3},
    {"input": "02_classic", "mod": "median-robin", "spp": 128, "runs": 3},
    {"input": "02_classic", "mod": "sah", "spp": 128, "runs": 3},
]


def generate_command(input, mod, spp):
    output = f"output/{input}_{mod}_{spp}spp.png"
    input = f"scenes/devoir4/{input}.json"
    mod = f"scenes/{mod}.json"
    command = f"{COMMAND} -- -i {input} -o {output} -a {mod} -n {spp}"
    return command
    

def parse_output(output):
    accel_structure = None
    intersections = None
    rendering_time = None
    
    # Parse Acceleration structure build in xxxxx
    accel_pattern = r'Acceleration structure build in \s*(\S+)'
    accel_match = re.search(accel_pattern, output)
    if accel_match:
        accel_structure = accel_match.group(1)
        if accel_structure.endswith("ms"):
            accel_structure = float(accel_structure[:-2])
        else:
            accel_structure = float(accel_structure[:-1]) * 1000.0

    # Parse intersections/#ray(traced): xxxxx
    intersections_pattern = r'#intersections\/#ray\(traced\):\s*(\S+)'
    intersections_match = re.search(intersections_pattern, output)
    if intersections_match:
        intersections = float(intersections_match.group(1))
    
    # Parse Rendering time: xxxxx
    rendering_pattern = r'Rendering time:\s*(\S+)'
    rendering_match = re.search(rendering_pattern, output)
    if rendering_match:
        rendering_time = rendering_match.group(1)
        if rendering_time.endswith("ms"):
            rendering_time = float(rendering_time[:-2])
        else:
            rendering_time = float(rendering_time[:-1]) * 1000.0
    
    return accel_structure, rendering_time, intersections


def run_command(cmd):
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=True
        )
        return result.stderr
    except subprocess.CalledProcessError as e:
        print(f"Error running command: {e}")
        print(f"stderr: {e.stderr}")
        return None
    except FileNotFoundError:
        print(f"Command '{COMMAND}' not found. Please check the command name.")
        return None


def main():
    data = pd.DataFrame(columns = ["input", "mod", "spp", "accel_structure", "render_time", "intersections_per_ray"])

    for run_config in BATCH:
        print(f"Config: {run_config["input"]}, {run_config["mod"]}, {run_config["spp"]} spp x{run_config["runs"]}")
        cmd = generate_command(run_config["input"], run_config["mod"], run_config["spp"])

        for i in range(run_config["runs"]):
            print(f"\tRun {i + 1}/{run_config["runs"]}...")

            output = run_command(cmd)
            if output is None:
                print("\tFailed to run command. Skipping this run.\n")
                continue

            accel_structure, rendering_time, intersections = parse_output(output)
            data.loc[len(data)] = [run_config["input"], run_config["mod"], run_config["spp"], accel_structure, rendering_time, intersections]

    run = random.randint(0, 100000)
    data.to_csv(f"renderer_bvh_stats_{run}.csv")
    groupby = data.groupby(["input", "mod", "spp"])
    groupby["accel_structure"].describe().to_csv(f"renderer_bvh_accel_structure_describe_{run}.csv")
    groupby["render_time"].describe().to_csv(f"renderer_bvh_render_time_describe_{run}.csv")
    groupby["intersections_per_ray"].describe().to_csv(f"renderer_bvh_intersections_per_ray_describe_{run}.csv")
    

if __name__ == "__main__":
    main()
